# Generated by Django 3.2.9 on 2021-12-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20211202_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='model',
        ),
    ]
