# Generated by Django 3.2.9 on 2021-12-03 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_rename_car_model_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='average rating'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rating'),
        ),
    ]
