# Generated by Django 3.2.9 on 2021-12-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_auto_20211203_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='avg_rating',
        ),
    ]
